### PR TITLE
Feature-Frontend: Create My-Reservations

### PR DESCRIPTION
**Pull request by sntakirutimana72**
## Milestone

- Users should be able to see the list of their own reservations.
- Users can cancel a pending reservation if they created it.

### CODE REVIEW

**Review by Chrissiku — APPROVED** [review]
# 🟢 Project Approved! 🏆

## Hi @sntakirutimana72 👋

Your project is complete! ✔️ 🏁

 Your code is very professional 💯 and I can see you have a great chance to be a Great Software Engineer ⛑️.

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉.

> **Note:** You can now take a break even if short before you move on to the next project. Happy 😄 Coding 🖥️! and Have a nice day 🌞.

## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Your code is top notch
- ✔️ No linter Errors

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by wale-prog — APPROVED** [review]
# APPROVED!!!! 🎉
## Hey @sntakirutimana72   😊 😃 

#### Great Job 😄 👏 You've done it. Nice completing this milestone 👍🏻 ✅ 

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by safar1212 — APPROVED** [review]
# APPROVED!!!! 🎉
## Hey @sntakirutimana72   😊 😃 

#### Great Job 😄 👏 You've done it. Nice completing this milestone 👍🏻 ✅ 

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by aliatayee — APPROVED** [review]
Hi @sntakirutimana72 

# Status: APPROVED!!! 

You've done a great job implementing all required behaviors.👍 Time to merge!

## Highlight! :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark:  No linter errors.

**Pull request merged**
